name: paid_leave_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  table_calendar: ^3.2.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/app_icon.png
  android: true
  ios: true